### ISSUE TITLE
Data to run the model

### ISSUE THREAD

**Issue by AlexandreJubert** [wk1984/Snow_Model_Fortran_Glen#1]
Hello,

I'm a computer graphics graduate science student at LIGUM, Université de Montréal, and in the context of my research I'm working on an implementation of the snowtran model developed by Liston & Sturm in 1998 "A snow-transport model for complex terrain", and its improvement in the 2007 paper "Simulating complex snow distributions in windy environments using SnowTran-3D", in C++, to simulate deposition of snow in 3D scenes, and its rendering.

I'm currently trying to run the fortran source code in this repository, with the parameter file found here : https://github.com/wk1984/SnowModel/blob/master/snowmodel.par
in one of your other repositories, but I'm missing two data files, respectively :
- "topo_veg/goa.topoveg.1km.gdat"
- "met/mm_cfsr_GOA_N_1979_2014.dat"

Sadly I lack the knowledge to replace these two files by any data from the Climate Forecast System or any other source, so do you know if these two files are available freely anywhere on the internet ?

If you're interested in what I'm working one currently I'll be more than happy to talk about it, 

you can contact me by email at alexandre.jubert[at]umontreal.ca

Sincerely yours

Alexandre Jubert

PS : here is my lab website if you're interested [http://www.ligum.umontreal.ca/](http://www.ligum.umontreal.ca/)

**Comment by wk1984** [comment]
Hi Alexandre,

This repository is just a backup from other people. I don't run it. So I 
can not answer your question. Sorry for that.

If my memory is correct, this repository is copied from 
https://github.com/aaarendt. However, I don't see it right now. I 
suggest you send your request directly to him.

Best,

Kang

**Comment by AlexandreJubert** [comment]
Hi,

Thanks a lot for your quick answer, I will contact him directly.

Best,

Alexandre
